// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search_intelligence.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^4.4.3";
var search_intelligence_default = defineTool({
  name: "search_intelligence",
  title: "Search intelligence items",
  description: "Full-text search across Hitek Info logistics intelligence items (headlines, summaries, impacts). Returns the most recent matches.",
  inputSchema: {
    query: z.string().min(1).describe("Keyword(s) to search for."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10)."),
    department: z.enum(["operations", "finance", "compliance", "commercial", "hr"]).optional().describe("Optional department filter."),
    severity: z.enum(["act_now", "this_week", "monitor", "fyi"]).optional().describe("Optional severity filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, department, severity }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("intelligence_items").select(
      "id, headline, summary, impact, department, severity, source_name, source_url, publication_date, event_date, country"
    ).neq("status", "archived").or(
      `headline.ilike.%${query}%,summary.ilike.%${query}%,impact.ilike.%${query}%`
    ).order("event_date", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (department) q = q.eq("department", department);
    if (severity) q = q.eq("severity", severity);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_intelligence_item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_intelligence_item_default = defineTool2({
  name: "get_intelligence_item",
  title: "Get intelligence item",
  description: "Fetch a single Hitek Info intelligence item by its UUID, including full impact and recommended action.",
  inputSchema: {
    id: z2.string().uuid().describe("Intelligence item UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("intelligence_items").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list_recent_intelligence.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_recent_intelligence_default = defineTool3({
  name: "list_recent_intelligence",
  title: "List recent intelligence",
  description: "List the most recent Morocco freight & logistics intelligence items from Hitek Info, optionally filtered by department, severity, or days back.",
  inputSchema: {
    days: z3.number().int().min(1).max(90).optional().describe("How many days back to look (default 7)."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 20)."),
    department: z3.enum(["operations", "finance", "compliance", "commercial", "hr"]).optional(),
    severity: z3.enum(["act_now", "this_week", "monitor", "fyi"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit, department, severity }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const since = /* @__PURE__ */ new Date();
    since.setUTCDate(since.getUTCDate() - (days ?? 7));
    let q = supabase.from("intelligence_items").select(
      "id, headline, summary, department, severity, source_name, source_url, publication_date, event_date, country"
    ).neq("status", "archived").gte("created_at", since.toISOString()).order("event_date", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (department) q = q.eq("department", department);
    if (severity) q = q.eq("severity", severity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_weekly_digest.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z4 } from "npm:zod@^4.4.3";
var get_weekly_digest_default = defineTool4({
  name: "get_weekly_digest",
  title: "Get weekly digest",
  description: "Fetch the Hitek Info weekly digest summaries (global, operational, financial) for a given ISO year & week. Defaults to the current week.",
  inputSchema: {
    year: z4.number().int().min(2020).max(2100).optional(),
    week: z4.number().int().min(1).max(53).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, week }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("weekly_digests").select("*");
    if (year) q = q.eq("year", year);
    if (week) q = q.eq("week_number", week);
    const { data, error } = await q.order("year", { ascending: false }).order("week_number", { ascending: false }).limit(10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { digests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hitek-info-mcp",
  title: "Hitek Info MCP",
  version: "0.1.0",
  instructions: "Hitek Info is a Morocco freight & logistics intelligence dashboard. Use these tools to search recent intelligence items, fetch a specific item by ID, list what happened in the last N days, or read the weekly digest (global/operational/financial).",
  tools: [
    search_intelligence_default,
    get_intelligence_item_default,
    list_recent_intelligence_default,
    get_weekly_digest_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
